### ISSUE TITLE
Use Web Workers

### ISSUE THREAD

**Issue by tsauerwein** [jseidelin/pixastic#1]
In Chrome 6+ it is possible to pass the ImageData object to a web worker, work on the pixels array and then return the object back to the main thread. This would also allow to show a progress bar.

An example can be found in Google's Chromabrush (http://www.chromabrush.com/):

```
* Main thread: http://code.google.com/p/chromabrush/source/browse/frontend/js/cb.filters.js
* Web worker: http://code.google.com/p/chromabrush/source/browse/frontend/js/filter.blur.js
```

**Comment by jseidelin** [comment]
Good idea. I've had web workers in mind for a while but have postponed any experiments until I get around to rewriting a bunch of other stuff. It's definitely something I'll look into at some point, though.

**Comment by drewlesueur** [comment]
The api may need to change to take ImageData instead of an Image to be able to use web workers.
Very exciting stuff. Thanks for this library.
