### ISSUE TITLE
Fliph and FlipV ignores image height on scree

### ISSUE THREAD

**Issue by masterperas** [jseidelin/pixastic#12]
When we flip an image that has been downsized on screen (img element is smaller than real image size) if we apply the fliph or flipv action pixastic draws a new canvas with the real image size instead of the constrained image.

Just wondering if this is done on purpose or if there is any reason not to do it by using the data array to draw the image

**Comment by michaelhaessig** [comment]
i running into the same issue. I know its closed, is there a fix for it ?
