### ISSUE TITLE
Pixastic don't work editing an image with slider

### ISSUE THREAD

**Issue by mllull** [jseidelin/pixastic#16]
I'm having trouble with pixastic library and jQueryUI sliders. I'm tring to do an Image Editor with this HTML5 Canvas library. I have this code:

``` js
$("#blur_slider").slider({                   
                value: 0.5,
                min: 0,
                max: 5,
                step: 0.1,
                slide: function(event, ui) {
                        $("#bright_slider_value").val(ui.value);
                        $("#test-image").pixastic("blurfast", {amount:ui.value})
                 }
        });
```

When I move the slider, the image is blurred properly, but when I put the slider on the value 0,the image still being blurred. Looks like it did the last blur on the blurred image and not on the original image.

Regards guys!

**Comment by jseidelin** [comment]
This version of Pixastic is no longer being developed.
